// Generated by scripts/generate-themes.mjs from design/themes.json and design/tokens.json; do not edit.

/** A theme beyond Begitra's own dark and light, by name. */
export interface PaletteTheme {
  readonly id: string;
  readonly name: string;
  readonly brightness: "dark" | "light";
}

export const PALETTE_THEMES = [
  { id: "ayu-dark", name: "Ayu Dark", brightness: "dark" },
  { id: "ayu-light", name: "Ayu Light", brightness: "light" },
  { id: "ayu-mirage", name: "Ayu Mirage", brightness: "dark" },
  { id: "catppuccin-latte", name: "Catppuccin Latte", brightness: "light" },
  { id: "catppuccin-mocha", name: "Catppuccin Mocha", brightness: "dark" },
  { id: "dracula", name: "Dracula", brightness: "dark" },
  { id: "gruvbox-dark", name: "Gruvbox Dark", brightness: "dark" },
  { id: "nord", name: "Nord", brightness: "dark" },
  { id: "one-dark", name: "One Dark", brightness: "dark" },
  { id: "one-light", name: "One Light", brightness: "light" },
  { id: "solarized-light", name: "Solarized Light", brightness: "light" },
  { id: "tokyo-night", name: "Tokyo Night", brightness: "dark" },
] as const satisfies readonly PaletteTheme[];

/** The id of a theme beyond Begitra's own. */
export type PaletteThemeId = (typeof PALETTE_THEMES)[number]["id"];
