//! `bench generate-tree`: a folder tree for the discovery benchmark, deterministic in shape:
//! `directories` directories over a few levels, `repositories` of them initialised with one
//! commit, and a handful of skip folders (`node_modules`, `target`) holding directories the
//! scanner must never enter.

use std::collections::VecDeque;
use std::fs;
use std::path::{Path, PathBuf};

use git2::{Repository, Signature};

use crate::{Error, Result};

/// Shape of the generated tree.
#[derive(Clone, Debug)]
pub struct Config {
    /// Root of the tree.
    pub out: PathBuf,
    /// Directories in total (below the root, skip folders included).
    pub directories: u32,
    /// Repositories among them.
    pub repositories: u32,
    /// Replace an existing tree.
    pub force: bool,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            out: crate::repos::discovery(),
            directories: 5_000,
            repositories: 50,
            force: false,
        }
    }
}

/// Counts of what was written.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Summary {
    /// Directories created, skip folders included.
    pub directories: u32,
    /// Repositories initialised.
    pub repositories: u32,
}

/// Fan-out of every level: 10 top folders, each with 10 children, and so on.
const FAN_OUT: u32 = 10;

/// Every this many directories one is a skip folder holding a subtree.
const SKIP_EVERY: u32 = 97;

/// Builds the tree at `config.out`. An existing tree is kept unless `force` is set; the
/// marker file `.begitra-bench-tree` guards against deleting a folder the bench did not make.
pub fn run(config: &Config) -> Result<Summary> {
    let out = &config.out;
    let marker = out.join(".begitra-bench-tree");
    if out.exists() {
        if !config.force {
            return Err(Error::Usage(format!(
                "{} exists; pass --force to replace it",
                out.display()
            )));
        }
        if !marker.exists() {
            return Err(Error::Usage(format!(
                "{} was not generated by bench; remove it by hand",
                out.display()
            )));
        }
        fs::remove_dir_all(out)
            .map_err(|source| Error::io(format!("remove {}", out.display()), source))?;
    }
    fs::create_dir_all(out)
        .map_err(|source| Error::io(format!("create {}", out.display()), source))?;
    fs::write(&marker, b"generated by bench generate-tree\n")
        .map_err(|source| Error::io(format!("write {}", marker.display()), source))?;

    let mut directories = 0u32;
    let mut repositories = 0u32;
    // Spread so the last repository lands before the directory budget runs out.
    let repo_every = (config.directories / (config.repositories + 1)).max(1);
    let mut queue: VecDeque<(PathBuf, u32)> = VecDeque::from([(out.clone(), 0)]);
    let mut counter = 0u32;
    while directories < config.directories {
        let Some((parent, depth)) = queue.pop_front() else {
            break;
        };
        for i in 0..FAN_OUT {
            if directories >= config.directories {
                break;
            }
            counter += 1;
            let is_skip = counter.is_multiple_of(SKIP_EVERY);
            let name = if is_skip {
                if i.is_multiple_of(2) {
                    "node_modules".to_owned()
                } else {
                    "target".to_owned()
                }
            } else {
                format!("d{counter:05}")
            };
            let dir = parent.join(&name);
            fs::create_dir_all(&dir)
                .map_err(|source| Error::io(format!("create {}", dir.display()), source))?;
            directories += 1;
            if is_skip {
                // A repository inside a skip folder must never be found.
                let hidden = dir.join("hidden-repo");
                init_repo(&hidden)?;
                directories += 1;
                continue;
            }
            if repositories < config.repositories && counter.is_multiple_of(repo_every) {
                init_repo(&dir)?;
                repositories += 1;
                // Found repositories are not entered, so their subtree does not count.
                continue;
            }
            if depth < 4 {
                queue.push_back((dir, depth + 1));
            }
        }
    }
    Ok(Summary {
        directories,
        repositories,
    })
}

fn init_repo(path: &Path) -> Result<()> {
    fs::create_dir_all(path)
        .map_err(|source| Error::io(format!("create {}", path.display()), source))?;
    let repo = Repository::init(path)?;
    let signature = Signature::new(
        "bench",
        "bench@begitra.local",
        &git2::Time::new(1_700_000_000, 0),
    )?;
    let tree_id = repo.index()?.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    repo.commit(Some("HEAD"), &signature, &signature, "init", &tree, &[])?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builds_the_requested_counts_and_refuses_foreign_folders() {
        let dir = tempfile::tempdir().expect("tempdir");
        let out = dir.path().join("tree");
        let config = Config {
            out: out.clone(),
            directories: 300,
            repositories: 5,
            force: false,
        };
        let summary = run(&config).expect("tree");
        assert!(summary.directories >= 300);
        assert_eq!(summary.repositories, 5);
        assert!(run(&config).is_err(), "exists without --force");
        let again = run(&Config {
            force: true,
            ..config.clone()
        })
        .expect("replaced");
        assert_eq!(again.repositories, 5);
        let foreign = dir.path().join("mine");
        fs::create_dir_all(&foreign).expect("mkdir");
        assert!(run(&Config {
            out: foreign,
            force: true,
            ..config
        })
        .is_err());
    }
}
